version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor:
      name: node/default
    resource_class: medium
    steps:
      - checkout
      - run: npm install
      - run: mkdir junit
      - run:
          command: npm run test:ci
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
          no_output_timeout: 5m
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
